name: Node.js CI

on:
  - pull_request

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js dependencies
        uses: bahmutov/npm-install@v1

      - name: Build
        run: npm run build

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js dependencies
        uses: bahmutov/npm-install@v1

      - name: Test
        run: npm run test

  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js dependencies
        uses: bahmutov/npm-install@v1

      - name: Lint
        run: npm run lint
